### ISSUE TITLE
Add SNOMED-CT codes to all the terms in COMORBIDITIES

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#10]
@coldunk can you link to the SNOMED RCPCH curated list here please.
Also the work you've already done mapping these SCTIDs to a Comorbidity, can you upload it here?
We may want to create a re-usable list in another repository, to enable this being shared as a Python package

**Comment by coldunk** [comment]
Thinking should link to live snomed ct browser neurodis refset

**Comment by eatyourpeas** [comment]
I have added to a [docs](https://github.com/rcpch/rcpch-audit-engine/tree/main/docs) directory in the main repo. I have also spent some time implementing [Hermes](https://github.com/wardle/hermes) from the remarkable @wardle which I envisage running as a local SNOMED server to supply the look up values.

**Comment by coldunk** [comment]
I am beginning to think this 'look-up engine + APIs' turning clinician-worded diagnoses into validated 'properly-worded' digital entities is 'the thing'.  Trying to think what that 'digital entity' would comprise of.  Think is an entity that means the same thing in the clinical world as the digital world!  As well as the engine 'serving' our audit dataset, could serve other things?!  Going to look up some Java-based work I did with karen h/and prayle in 2016 that got the snomed ct neurodis refset work started. Mulling!!

**Comment by wardle** [comment]
Thanks. I am generally defining my code lists using the SNOMED expression constraint language. For example, one can test membership, or expand a valueset of "<< 128613002" and get all seizure disorders. I also build ECL on the fly from either ICD-10 or ATC codes. You can see what I've been doing for an MS project if you like - I am building code lists declaratively using a union of all three depending on need - e.g. see the medications and diagnoses listed from [line 33 of this project-specific code](https://github.com/wardle/pc4/blob/b3d2da23000b0df04e2b8b6a393995d5260e0ba5/pc4-server/src/com/eldrix/pc4/server/modules/dmt.clj#L33). Glad you got hermes working. I am now layering more complex abstractions above hermes, and my dm+d implementation - e.g. see a [more generic 'code lists' abstraction](https://github.com/wardle/pc4/blob/main/pc4-server/src/com/eldrix/pc4/server/codelists.clj) that basically has inclusions and exclusions specified as a mix of ECL, ICD10 and ATC. I am planning on spinning that out into its own service, so code lists on demand - a bit like [Ben Goldacre's code lists](https://www.opencodelists.org) project but derived computationally rather than curated manually.

**Comment by eatyourpeas** [comment]
So this is now working in no small point thanks to you @wardle thank you. url if you want to use is [here](http://rcpch-hermes.uksouth.azurecontainer.io:8080/v1/snomed/) . We also have an instance of deprivare running [here](http://rcpch-deprivare.uksouth.azurecontainer.io:8080/v1/uk/lsoa/)
We are very grateful and I am still up for that chat?  Closing this issue here though.

**Comment by wardle** [comment]
Glad it is working. Let me know if any issues. I'll email about another meet-up! 

You should also see how graph APIs work across these datasets. Composing functionality with data in a unified graph with independent resolvers provided by different subsystems and services is a super power to building compelling user interfaces. 😀

**Comment by wardle** [comment]
PS. You might also see [https://github.com/wardle/dmd](https://github.com/wardle/dmd) which runs a tiny micro service to provide access / resolution to the UK dm+d and address your #24. It composes nicely with SNOMED because of course they share common identifiers. The key to the graph above - so I walk from SNOMED into dm+d and get ingredients and then walk back to SNOMED to understand those ingredients, for example.
