### ISSUE TITLE
Creating a way to change user organisation

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1011]
Is there a way to create a route to changing users organisation or Trust from the user interface? Currently we are just deleting the users and re-adding, but this doesn't always work seamlessly. 

Open to other options/work arounds too.

**Comment by eatyourpeas** [comment]
We did discuss this before. Users cannot be deleted, only disabled, since their user id is associated with any activity with different patient records for their original organisation. Please don't delete anything in the user admin. 
In the original brief we were not asked I don't think to give users multiple user accounts. There is an issue requesting this in the backlog (#879) but to fix it will involve a refactor of the models, probably creating OrganisationEmployer as a separate join table between user and organisation. Of course this is doable but not a simple fix. How urgent is it?

**Comment by eatyourpeas** [comment]
I think this issue is subtly different to #879 but allied. For the moment I think this is fixed, in as far as the users concerned have been moved to be affiliated with their new organisation.
Having multiple employers (active and inactive) is really the subject of #879 so I will close this and continue the conversation over on #879
