### ISSUE TITLE
Adding causes to the platform 

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1045]
Hiya!

Could we please have the following causes added onto the platform? (Sorry there's quite a few!)

Colin has approved.

1. E12 ID 4723 POLG mitochondrial disorder
2. E12 ID 6260 PRRT2 genetic mutation
3. EP12 ID 4905: Has genetic diagnosis as deletion of 10p15.3 
4. EP12 ID 4609:  16q24.3 pathogenic variant 
5. Autosomal dominant Usmani-Riazuddin syndrome 
7. CTID: 28781004 | Craniopharyngioma, adamantinomatous
8. SCTID: 699254009 15q13.3 microdeletion 
9. SCTID: 471282000 Chromosome microdeletion 

Thank you!

Saleema

**Comment by eatyourpeas** [comment]
Can I check here? paging @coldunk 
`471282000` has the broad name of `chromosome microdeletion` which in snomed speak is a **finding**, where as `699254009` (15q13.3 microdeletion) is a **disorder**
Microdeletion is a very broad term and we have added a lot of deletions, microdeletions, microduplications etc already which are their own entities. I am pretty sure they have alll been disorders rather than findings (though would need to confirm this).  It is difficult to remove items once they have been added since users will use them...
So I have added 1-7 but not number 8. Please let me know if you still want me to do this...
