### ISSUE TITLE
Database back up

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#105]
Possibly too big an issue to be saved as a single item so this is really a placeholder.
Facility is need for DB backup 
- [ ] create cron job or similar to export DB to SQL dump
- [ ] persist SQL dump within Azure / S3 or similar
- [ ] facility to roll back to previous version

**Comment by pacharanero** [comment]
Azure managed Postgres DB has an inbuilt database backup facility which is now enabled. https://portal.azure.com/#@rcpch.ac.uk/resource/subscriptions/99e313f5-79fe-4480-b867-8daf2800cf22/resourceGroups/RCPCH-Dev-API-Epilepsy12/providers/Microsoft.DBforPostgreSQL/flexibleServers/e12db/backupAndRestore
Backups are made on a nightly basis and retained for 35 days (the maximum)
We can use offline tools like PGAdmin to take backups and save them in a secure place if we need longer backup retention.

**Comment by pacharanero** [comment]
UPDATE: Since moving to VPS deployment we have changed the backup strategy so that the Live VPS is backed up using Azure's inbuild disk image backup. As a basic standard backup procedure this is adequate, however for more granular backup and restore we may wish to institute an "second tier" alternative backup strategy as well, which will be detailed in another Issue
