### ISSUE TITLE
Change the causes question on platform to "non-mandatory"

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1125]
Hi Michael & Simon, 

Whilst we figure out a better process for adding causes onto the system can we please make the section non mandatory. 

So we would like to keep this question mandatory:
![image](https://github.com/user-attachments/assets/482dc84c-99a2-4b9f-a3a2-110d9d32e70c)

but then make the follow up question non-mandatory 

![image](https://github.com/user-attachments/assets/ae456b12-617e-4505-8906-0d1fc4ff536a)

We have had a lot of queries come in so would ideally need this as soon as possible. 

Let me know if there is anything you need from me.

Thanks
Saleema

**Comment by eatyourpeas** [comment]
Thanks Saleema. This is a shame - we have put a lot of work into the epilepsy causes and by making it optional your users will nolonger fill it out. The users already have an option to say that no cause is known, so if a cause is known and they don't have to enter it you will lose all this data.

You are welcome to add new causes to the admin yourself in the EpilepsyCause table. The work flow is first to search for the condition on the snomed browser to see if there is a snomed term. You then add the preferredTerm and the term to the admin along with the snomed-ct id. I can add new causes quite quickly - within 24 hours if this is a problem - but I have found in the past that I have had clinical questions about the causes requested and want to be sure that the causes that are added are the right ones. Once a cause has been added and used in a record, it can't really be removed. 

I have produced a fix and it is all ready to merge. Let me know that this really is what is preferred and I will go ahead.

**Comment by mbarton** [comment]
I agree with Simon it would be a shame to lose any information about the cause just for expediency of filling in the audit.

I wonder if a “propose a new cause” feature would help? With that they could fill in the cause free text and you can then review them after submission, updating them with the SNOMED code etc once it’s been clinically confirmed?

My thinking is that it brings the process of adding a cause “in the box” rather than email and doesn’t block submission? 

We can signpost in the free text option that it is a suggestion, will need to be confirmed by the audit team and they may come back to request more information

**Comment by nikyraja** [comment]
Hi both, thanks for your replies and I completely agree with everything here. 

To give a bit more context, and apologies for not doing so sooner, we've had a few road blocks in adding new causes from our end - we've noticed a lot of genetic causes being requested and we're not too confident on how these should appear in the platform, so Colin and I have been speaking with a epilepsy genetics expert to work this out. This is taking a bit of time as in a lot of ways this is bigger than our platform or audit.. 

As we are nearing the January deadline, I don't want to stop users from completing the records ad therefore their data not being included in the annual analyses just because we (Colin and I) haven't nailed the genetic causes yet. So, I was hoping that just until the January deadline we could make this question non-mandatory, and then switch it back for cohort 7 once we've figured out the genetic causes.

This wouldn't be a long term solution, because as you've said, if users don't have to fill something out they won't and we want to get a complete dataset. But hopefully this describes our rationale.

**Comment by nikyraja** [comment]
An “in the box” solution to adding causes would be more streamlined than email, however the work flor that Simon set up is very easy and has worked well over this past year. Its more just the extra complexity of genetic causes that is blocking things now, so there may not be a need to change anything.

**Comment by eatyourpeas** [comment]
that sounds fine @nikyraja I understand. Epilepsy is increasingly genetic now, I sympathise. There are so many chromosomal and genetic abnormalities that are known it does feel the drop down with all the different ones will quickly be the wrong way to invite users to choose. Perhaps one way would be, if the child does not have a defined syndrome but does have a genetic or chromosomal mutation, we invite them just to call the cause 'genetic' and leave it at that.

If we make the box optional, it will be difficult to make it mandatory again, as those people who had completed the forms without the cause there will find their forms nolonger 100% when we flip the switch back. We could probably cross that bridge when we come to it but wanted to make sure you had thought of that. Possibly we could make it mandatory for cohort  7 since there will still be time for people to go back and put causes in.

**Comment by nikyraja** [comment]
Thanks Simon, and thanks for flagging the risk of making questions mandatory again. I think if we make the switch early on for cohort 7, for example in Jan/Feb, that will give user enough time to go back and edit the forms. 

We are close to solving, but I like the other ideas you and Michael suggested so will talk to Colin and create another issue if we need. 

Thank you!
