### ISSUE TITLE
New causes to be added to the platform 

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1136]
Hi Simon, 

Can we add these causes to the platform please?

There's quite a few but because the question is no longer mandatory, we don't need it as soon as possible. So there's no rush. 

See attached the spreadsheet with the list of causes with the codes (where applicable) 

[Causes to be added to the Platform.xlsx](https://github.com/user-attachments/files/18199737/Causes.to.be.added.to.the.Platform.xlsx)

Thanks!

**Comment by eatyourpeas** [comment]
Thank you @SAbdin93 

Going through this list I have questions really mostly directed @coldunk, the summary of which is that it strikes me there is confusion between what you are calling a *cause* and what you are calling a *syndrome*

## Spreadsheet
Before that, specific issues with your spreadsheet
- 1163072008 - parechovirus infection - this is already covered with encephalitis
- 253153000 - cortical dysplasia already exists in the database
- 767263007 - 22q11 - this is in your list twice
- Is trisomy 21 really a cause of epilepsy?
- myoclonic-astatic epilepsy (Doose): this is not a cause of epilepsy
- ReNU: this already exists in the database
- GNB1 related disorder: this already exists in the database
- SCN1A does have a SNOMED code and is in the database already: 230437002
- GEFS stands for Genetic Epilepsy with Febrile Seizures and so is not really a cause: it already exists in the Syndromes table
- PCDH-19 related epilepsy does have a SNOMED code and is in the database already: 888801000000105. Note that as with some other examples, it exists both in the Syndromes table as well as the Causes table.

### Suggested additions
This means that of the 25 requests I am suggesting only 17 additions, of which 11 have SNOMED codes and 6 are added to the database without. I summarise them in a table below.
As an aside, can I question the inclusion of Down's sy (trisomy 21) as a cause of epilepsy? Is this a cause or is it just recognised that seizures are more prevalent in T21?

| **SNOMED-CT** | **Name** |
|----|---|
| 95643007 | Autoimmune encephalitis |
| 734434007 | ALDH7A1 related pyridoxine dependent epilepsy |
| 764522009 | NPRL3 gene (familial focal epilepsy with variable foci) |
| 699310000 | Phelan McDermid Syndrome (22q13 deletion syndrome) |
| 767263007 | Chromosomal disorder 22q11 deletion syndrome |
| 17231009 | foetal valproate syndrome |
| **41040004** | **Trisomy 21** |
| 87191000119100 | Ganglioglioma |
| 438583008 | Congenital bilateral perisylvian syndrome | 
| 4945003 | microgyria | 
| 371121002 | Neonatal stroke |
| | KCNK4-related neurodevelopmental disease | 
| | EEF1A2-Related Neurodevelopmental Disorder |
| | KCNH1-related epileptic encephalopathy |
| | 2p13.3 deletion |
| | COL4A1 or COL4A2-related disorder |
| | PHF21A-related disorder |



## Syndromes vs Causes - a broader issue
There is reference in this list to Syndromes, in particular **GEFS** and **Doose**. Syndromes are using a different look up. Currently we have:
| syndrome |
|---|
| Self-limited (familial) neonatal epilepsy |
| Self-limited (familial) infantile epilepsy |
| Self-limited familial neonatal-infantile epilepsy |
| Self-limited epilepsy with centrotemporal spikes |
| Self-limited epilepsy with autonomic seizures |
| Childhood occipital visual epilepsy |
| Photosensitive occipital lobe epilepsy |
| Mesial temporal lobe epilepsy with hippocampal sclerosis |
| Familial mesial temporal lobe epilepsy |
| Sleep-related hypermotor (hyperkinetic) epilepsy |
| Familial focal epilepsy with variable foci |
| Epilepsy with auditory features |
| Genetic epilepsy with febrile seizures plus |
| Myoclonic epilepsy in infancy |
| Epilepsy with myoclonic absences |
| Epilepsy with eyelid myoclonia |
| Childhood absence epilepsy |
| Juvenile absence epilepsy |
| Juvenile myoclonic epilepsy |
| Epilepsy with generalized tonic–clonic seizures alone |
| Early infantile DEE |
| Epilepsy of infancy with migrating focal seizures |
| Infantile epileptic spasms syndrome |
| Dravet syndrome |
| Etiology-specific DEEs |
| **KCNQ2-DEE** |
| **Pyridoxine-dependent and pyridox(am)ine 5′ phosphate deficiency DEE** |
| CDKL5-DEE |
| **PCDH19 clustering epilepsy** |
| **GLUT1DS-DEE** |
| Sturge–Weber syndrome |
| Gelastic seizures with HH |
| Epilepsy with myoclonic–atonic seizures |
| Lennox–Gastaut syndrome |
| DEE or EE with spike-and-wave activation in sleep |
| Febrile infection-related epilepsy syndrome |
| Hemiconvulsion–hemiplegia–epilepsy |
| Rasmussen syndrome |
| Progressive myoclonus epilepsies |
| Epilepsy with reading-induced seizures |

If you scan down the list you will see that there are few items in there that are duplicated in the causes list. I have highlighted a few. They tend to be specific gene or chromosomal duplication/microduplication/deletion/microdeletions.

For the longer term - might the epilepsy data group consider what to do about the duplicates in both tables and more generally how to handle genetic associations vs genetic causes? **The difficulty is that once a cause or a syndrome is added, it cannot be removed** since we must assume that it will be associated with a child's record somewhere.

## A suggestion
I should qualify this by saying that I am generally not very good at classification (you should see me load the dishwasher) and as I have said before tend to be more of a lumper than a splitter. That said it feels to me there must be an inclusive way to divide out these lists a little to allow users to find the options they need to describe what they see more easily.
My suggestion, for what it is worth, might be to remove the causes as it is currently organised altogether and replace simply with some short questions:
1. Does your patient have one of the following genetic mutations? [UBE3A, SLC2A1, MECP2, SCN1A, STXBP1, CDKL5, KCNQ2, SCN2A, KCNT1, ARX, FOXG1, PCDH19, GRIN2A, etc...]
2. Does your patient have one of the following chromosomal rearrangements? [2q23.3 Microdeletion Syndrome, 14q32 deletion syndrome (disorder), 16p11.2 deletion syndrome is, 6p11.2 microduplication syndrome, 10p 15.3 microdeletion syndrome, 16q 24.3 microdeletion syndrome, 2p 13.3 deletion, etc...]
This potentially could be subdivided by duplication vs deletion, maybe focusing on the chromosome, region and band but leaving out the sub-bands as there is so much heterogeneity here.
3. Does your patient have an identified phenotype? [Rett, Angelmann, Dravet, Rasmussen, Lennox-Gestaut]
5. Does your patient's epilepsy conform to an identifiable epilepsy syndrome? [Self-limited (familial) neonatal epilepsy, Self-limited (familial) infantile epilepsy, Self-limited familial neonatal-infantile epilepsy, Self-limited epilepsy with centrotemporal spikes, Self-limited epilepsy with autonomic seizures, Childhood occipital visual epilepsy, Photosensitive occipital lobe epilepsy, Mesial temporal lobe epilepsy with hippocampal sclerosis etc..]

# Main Questions
***Before making any changes therefore would it be possible to confirm:***
1. are you happy with the 16 additions I have identified?
2. can you confirm you would like trisomy 21 added as a cause?
3. Do you want Doose (myoclonic/atonic epilepsy) added to the syndromes table?

**Comment by coldunk** [comment]
Thanks SimonYes causes are often unclear in our world.  If a child had a trisomy and epilepsy, you would assume causal relationship. Is not a provable association. Epilepsy much more common in Down compared to standard rates.  At some point could consider ways to nail associations as this interplay between a cause, an epilepsy and a commodity is quite dynamic.  Unpicking DEEs is all the rage!!!Colin

**Comment by eatyourpeas** [comment]
That is great thank you @coldunk I will go ahead with all 17 then. 
Are you wanting Doose in the the syndromes table or not?

**Comment by coldunk** [comment]
It is now known as this?  Epilepsy with myoclonic atonic seizures (Doose syndrome)if it’s already there, the inputter just needs to be pointed to it rather than looking in causes!ColinOn 21 Dec 2024, at 13:19, Simon Chapman ***@***.***> wrote:﻿
That is great thank you @coldunk I will go ahead with all 17 then.
Are you wanting Doose in the the syndromes table or not?
