### ISSUE TITLE
Tab 4 Multiaxial diagnosis

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#140]
DES narrative text can be:

A child or young person's epilepsy should comprise at least 1 type of epileptic seizure.  Their diagnosis may comprise and be accompanied by other types of epileptic, uncertain or non-epileptic episode. Add each type of episode, completing the initial D, E, S stages of the DESSCRIBE tool. 

Rephrase "When did the episode happen?" as "When did the first episode of this type happen?"

the 'episode definition' field under 'When' is a bit different now as all children will have epilepsy by definition and these features are listed within our inclusion criteria
however there is value to retain here.  Can the 4th stem though be removed 'the patient was diagnosed as epilepsy for another reason'.

D Description is all fine

E needs a bit of rewording:
should be 
E Epileptic
'Is this episode(s) epileptic?'  (rather than 'Is it Epilepsy?')
with the choice boxes being 'Epileptic' 'Non-epileptic' 'Uncertain'

under choice Uncertain can the 'Epilepsy Diagnosis Unclear' box be deleted.
 
S Seizure type
The question 'Were any of the epileptic seizures convulsive?' should not be here in the DESSCRIBE sequence as it is a general question to determine whether the child needs an ECG and is not required for each seizure type. I think the question should go in the epilepsy context tab and renamed as 'Were any of the seizures convulsive'?

regarding the seizure choice questions:
can it be such that a box can be unchecked by clicking it as at the moment you can only uncheck a box by selecting another

can the non-motor manifestations  allow multiple to be checked
can the 'EEG manifestations' be retitled 'location' and allow multiple to be checked

the generalised onset button is not working

S Syndrome
can this be retitled 'Syndrome' rather than 'Syndromes'
is the diagnosis active is a redundant question and field.  can this be removed?

C Cause
Can it say 'Has a cause for the epilepsy been identified?' rather than 'is there a know cause?'

RIBE Comorbidities
can it say "Are there any relevant impairment, behavioural, educational or emotional problems?'

**Comment by eatyourpeas** [comment]
- [x] refactor label seizure_onset_date in Episode from "When did the episode happen?" to "When did the first episode of this type happen?"
- [x] refactor template label from 'Is it Epilepsy?' to 'Is this episode(s) epileptic?' in epilepsy.html
- [x] refactor EPILEPSY_DIAGNOSIS_STATUS from 'epilepsy', 'non-epilepsy', 'uncertain' to 'epileptic', 'non-epileptic', 'uncertain'
- [x] remove Epilepsy Diagnosis Unclear from 
- [x] remove 'Were any of the epileptic seizures convulsive?' field from MultiaxialDescription model and view and template
- [x] add 'Were any of the seizures convulsive' to EpilepsyContext model, view and template
- [x] focal seizure boxes allow deselect on click, set field in model to False
- [x] generalised onset in multiple selection multiple toggle fix (already fixed in previous PR)
- [x] Refactor 'Syndromes' to 'Syndrome' in multiaxial_diagnosis_form.html
- [x] remove 'Is the diagnosis active' from Syndrome model, view and template
- [x] refactor  'Has a cause for the epilepsy been identified?' rather than 'is there a know cause?'
- [x] refactor Are there any relevant impairments (behavioural or educational)? to "Are there any relevant impairment, behavioural, educational or emotional problems?'
