### ISSUE TITLE
Tab 5: Milestones

### ISSUE THREAD

**Issue by FridahC** [rcpch/rcpch-audit-engine#207]
This tab doesn't change colour to **magenta** if all the questions are completed

**Comment by eatyourpeas** [comment]
Thank you @FridahC 

Some context here - scoring each field is necessarily dynamic because we have chosen a strategy that saves each field as it is completed. This means there is necessarily a changing denominator in the score, depending on what the user has selected so far. For example, if the user records that no referral has been made to an epilepsy nurse specialist, they cannot be expected to provide date referred and date seen, so the denominator will count two less if referral has not been made than if referral has been made. The total expected score for the epilepsy nurse section then has a minimum of 1 (referred vs not referred), which rises to 3 if referred. The conditional logic therefore gets complicated, particularly when counting fields in related tables, as happens with episodes, syndromes and comorbidities in the multiaxial diagnosis form. In episodes, for example, a user could in theory enter several different episodes of differing seizure types, none of which are epileptic, and therefore all those entries would be counted, but the minimum score would still not be met as at least one episode must be epileptic.

With that in mind this will take some testing of all the different permutations in each form to make sure there are no errors. I have fixed this form for now but leave the issue open until you are happy that this form is now scoring correctly.
**I would be grateful if you could close this issue when you are happy that this has been dealt with for this form.** If you find further errors in scoring with this form, please leave some detail of what you entered and what you observed below to troubleshoot further.

**If you find scoring errors with other forms, please open a new issue with detail on what has not scored if possible.**

**Comment by FridahC** [comment]
Thanks @eatyourpeas 
I have completed all the fields in the form and I would then expect the score to be 100%  and not 88%.  See attached screenshots. I think something is still not right


<img width="661" alt="1" src="https://user-images.githubusercontent.com/115698255/201893116-39b3118d-a98a-49a9-a3c4-41b506d82d33.PNG">
<img width="561" alt="2" src="https://user-images.githubusercontent.com/115698255/201893119-e29128f9-091e-4862-839b-cd1aec299a47.PNG">
