### ISSUE TITLE
GitHub actions failing deploy

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#254]
Any pushes to live or merging PRs no longer trigger a build and deploy to azure. 
The code on the live branch currently is some commits ahead of what is currently viewable on rcpch.tech

**Comment by pacharanero** [comment]
This was caused by GitHub Action workflow files inadvertently being deleted from the `live` branch (6039db25f16b7c341da0df6c7d41b7e2360f1f40)

I would advise caution when merging between major branches, as there should be **multiple** deployment workflow files present in the .github/workflows directory, one for each major branch `live`, `staging` and `development`. It's sometimes easy to merge from one to the other and lose one. Ideally if we are following our code promotion strategy, which means merging development > staging > live, then this should not happen

**Comment by pacharanero** [comment]
Has been fixed via d81e8809010e6e7a787952dffc83c83624eadb3d, closing
