### ISSUE TITLE
hero section in dev not scaling properly

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#283]
# The problem
The hero section's vertical scaling is off after my PR #279 
![image](https://user-images.githubusercontent.com/68898006/224480377-f04cc351-2640-4974-8626-1c00e9dbc26c.png)

# Proposed solution
- the problem probably lies in CSS declarations I did for the hero container / background (setting size as `vh` / relative). Will find the issue and fix

**Comment by eatyourpeas** [comment]
The main thing is that the style has to match other RCPCH microsites. Examples include:
[here](https://dataportal.rcpch.ac.uk)
and 
[here](https://childprotection.rcpch.ac.uk)

If you look at the html/css you will see that I have placed the wallpaper image across the screen and covered it with opacity, over which I have placed the text. To allow it to resize based on screen size I have used vh - I did this because we demoed the site a while back at RCPCH where the screens are extra wide and it did not stretch to fill with width.

The wallpaper to choose from is either the cog background or the child hugging their knees background. I think the cog is more appropriate for an audit rather than sad looking children which is not an image we want to project for children who should be living well with minimal or no impairment from their longterm health condition.

Feel free to make whatever adjustments you like to match the style as best you can.

**Comment by anchit-chandran** [comment]
Thanks for the tips Simon - ended up sorting with these declarations 

![Image](https://user-images.githubusercontent.com/68898006/224655482-494d10ee-b29b-4694-abfb-ee7de7e45f4e.png)

**Comment by anchit-chandran** [comment]
fixed with #289 , will close when merged
