### ISSUE TITLE
MRI and EEG performed dates cannot be blank

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#288]
MRIs and EEGs can be requested but currently the form for Investigations cannot be complete until the performed date box is also filled in order to calculate the time elapsed between the two dates. For some patients the request will have been made but the test will not yet have been performed at the time of audit submission.

Should we allow users to leave the performed date boxes to be blank (and so fail the measure) but at least complete the form, or insist that both dates are provided for the form to be marked as complete?

**Comment by coldunk** [comment]
HmmmIt is requested, not done, but pendingIn my mind this is both complete but ‘fails the kpi’This is around how we portray the left completion dials in this state…Is there no route to showing this as complete despite MRI pending??Data Completion has never equated to kpi fulfilment…Sent from my iPadOn 12 Mar 2023, at 18:48, Simon Chapman ***@***.***> wrote:﻿
MRIs and EEGs can be requested but currently the form for Investigations cannot be complete until the performed date box is also filled in order to calculate the time elapsed between the two dates. For some patients the request will have been made but the test will not yet have been performed at the time of audit submission.
Should we allow users to leave the performed date boxes to be blank (and so fail the measure) but at least complete the form, or insist that both dates are provided for the form to be marked as complete?

**Comment by eatyourpeas** [comment]
Currently MRI performed is a required field, so the user cannot complete the investigations form without it. In the Medicines section we have a start date as mandatory but the stop date is optional and hidden with a toggle button that makes it appear if the user wants to enter historical medicines. We could do the same thing with MRI, but then of course the performed date would not be required, meaning users might tend not to complete it, even though they may have it available, and it would mean in those cases we would not be able to calculate the time elapsed between the request and the scan.

**Comment by eatyourpeas** [comment]
Fixed as part of a bigger refactor and validation of dates
