### ISSUE TITLE
Items appearing multiple times in dropdown lists

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#304]

**Comment by AmaniKrayemRCPCH** [comment]
Relevant issues raised. 

- [ ] Clinician access page > patient registration form: 4 Multiaxial diagnosis > Comorbidities > Are there any relevant impairment, behavioural, educational or emotional problems? Some of the options appear multiple times in the dropdown like Autism spectrum disorder
- [ ] Clinician access page > patient registration form: 4 Multiaxial diagnosis > Cause > What is the main identified cause of the epilepsy? Some of the options appear multiple times in the dropdown, for example Andermann syndrome  and Phytanic acid storage disease
- [ ] Asperger’s disorder is repeated 4 times as an option in the Comorbidities drop down list

**Comment by AmaniKrayemRCPCH** [comment]
Each dropdown has multiple duplicate items, but ive only attached a screenshot of one. 

![Image](https://user-images.githubusercontent.com/126471383/226620803-f06ee39c-2ee6-46d0-8407-fa60d0683816.PNG)
![Image](https://user-images.githubusercontent.com/126471383/226620802-46c4d53c-c211-4631-ac6b-60b256a7e24d.PNG)

**Comment by eatyourpeas** [comment]
This is a tricky one and not really a bug since it is functioning correctly. It comes down to where we pull our problem lists from which currently for comorbidities and causes is SNOMED. Although they look like duplicates, they are not duplicates, just multiple ways of describing the same thing - SNOMED has a preferredTerm attribute, but there are also synonyms and fully accepted names. So the issue here is actually a wider question for discussion: do we do more work on identifying and curating a SNOMED-CT Refset or do we use a dropdown list that I think you have already provided in the past?
That question is aimed @coldunk

**Comment by coldunk** [comment]
NHSDigital SNOMED CT Browsertermbrowser.nhs.ukThis is the RCPCH neurodis refset.  Eg. It has asd listed once under parent of pervasive development disorder.  I think is closest thing.  Have emailed Robert Robinson to check not another refset not aware of.  Sent from my iPadOn 21 Mar 2023, at 20:55, Simon Chapman ***@***.***> wrote:﻿
This is a tricky one and not really a bug since it is functioning correctly. It comes down to where we pull our problem lists from which currently for comorbidities and causes is SNOMED. Although they look like duplicates, they are not duplicates, just multiple ways of describing the same thing - SNOMED has a preferredTerm attribute, but there are also synonyms and fully accepted names. So the issue here is actually a wider question for discussion: do we do more work on identifying and curating a SNOMED-CT Refset or do we use a dropdown list that I think you have already provided in the past?
That question is aimed @coldunk

**Comment by eatyourpeas** [comment]
Epilepsy12 meeting
SNOMED-CT vs ICD-11 vs existing syndrome and cause lists
Decision
- [ ] for uncategorised syndromes suggest question icon in ui that emails the audit team with requests to add new items to list
- [x] implement new table for syndromes with M2M relationship with MultiaxialDiagnosis
- [x] new table to persist syndromes to be used as look up, with associated SNOMED-CT refset list and ICD11 list
- [x] @coldunk to provide the main list - @eatyourpeas to send lists through to be curated

**Comment by eatyourpeas** [comment]
I will close this and create a new issue for the general issue of contacting RCPCH to add new items to dropdowns
