### ISSUE TITLE
Updating user details

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#323]
- [x] After editing a staff user's details, there's no confirmation that the changes had taken place and no easy way to return to the staff list. amani.krayem@rcpch.ac.uk, 20/03/2023
- [x] Unable to change user's role. amani.krayem@rcpch.ac.uk, 22/03/2023

**Comment by eatyourpeas** [comment]
I think this is fixed already in the development branch. @anchit-chandran @pacharanero could you please check you are happy with the workflow and redirects? A successfully saved user should redirect to the user table updated with the new user and send an email to the user with a link to confirm account and change password. A message appears above the table notifying user has been saved. Any errors in the form preventing the user being saved should be redirected to the form with error messages in the appropriate field.

**Comment by anchit-chandran** [comment]
Creating a new user works + error handles appropriately / redirects to all users table with success message at the top etc

However, the edit views, though successful, don't show the success messages in `user_management_views.edit_epilepsy12_user`

Can't confirm if emailing works probably because I'm running from local?

**Comment by eatyourpeas** [comment]
fixed in #447
