### ISSUE TITLE
Completing syndrome entry when data is missing

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#325]
The form allows you to click and save that the Sydrome entry is complete without the user having entered or selected an identifiable syndrome from the drop down list but once you have clicked it as being complete the form then flags the Syndrome Name section as an Uncompleted field

epilepsy12@rcpch.ac.uk, 20/03/2023

**Comment by eatyourpeas** [comment]
Once the syndrome has been entered it is easy to edit. It is easy to see the field is incomplete and needs editing as there is a blue target rather than a pink tick next to syndrome. All the user has to do is edit the syndrome, select the missing field and that should update the dial. The difficulty is that if you force the user not to progress until the box is filled it will mean that we do not implement the 'save as you go' idea for this section. What work flow would you prefer us to have here? Happy to try and implement something else if I can't persuade you to keep this :)

**Comment by eatyourpeas** [comment]
further signposting on incomplete comorbidity added in table

**Comment by nikyraja** [comment]
Thanks Simon - I'm happy to keep this as is. I like the 'save as you go' concept, but flagging the entry with 'uncompleted field' makes this easier for users - best of both worlds! 

Could we change the text to 'incomplete' rather than 'uncompleted' please?

**Comment by pacharanero** [comment]
> Could we change the text to 'incomplete' rather than 'uncompleted' please?

Yes, this can be done, it is hardcoded in multiple files so would need to search the codebase for 'uncompleted' and replace all. @anchit-chandran happy for you to do this one

**Comment by anchit-chandran** [comment]
Done. Will close
