### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#332]
- [ ] There doesn't currently seem to be a quick way to navigate from an individual patient's dataset back to the patient list so could one be added? (i.e. currently you have to go back to the Clinician access tab and then click on the View All patients tab to get there). epilepsy12@rcpch.ac.uk, 27/03/2023
- [ ] No quick way to navigate from creating patient/user to the patient/user list. amani.krayem@rcpch.ac.uk, 27/03/2023
- [ ] No quick way to navigate from editing patient/user details to the patient/user list. amani.krayem@rcpch.ac.uk, 27/03/2023
- [ ]

**Comment by eatyourpeas** [comment]
This should be possible and I agree it will be annoying for users to constantly be redirected to their hospital screen.

**Comment by anchit-chandran** [comment]
This is potentially fixed in one of your dev-fixes recently @eatyourpeas. Currently, when you create/edit a patient/user, you get sent back to this screen. Is this the correct implementation?

![Image](https://user-images.githubusercontent.com/68898006/228549507-045b43ae-654e-4783-9c18-3fcfd098cfcb.png)

**Comment by eatyourpeas** [comment]
Implemented with new button in steps.html
