### ISSUE TITLE
Adding Hospital Trust to the "National" patients view

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#351]
Add a column to show the Trust for each patient in the 'National' view

**Comment by eatyourpeas** [comment]
@AmaniKrayemRCPCH Can I check that this is definitely needed? An extra column will be difficult to shoehorn into the table and the child's organisation can currently be identified by selecting them..

**Comment by nikyraja** [comment]
Here, we are looking for a way for the E12 team to easily identify/sort/filter patients by trust. So it doesn't have to be by adding another column, as i appreciate your point on having too many etc. 

Perhaps we can add a drop down menu for Trusts on the national view only? Or if you have another idea on how we could achieve this without making the tables too clunky?

**Comment by eatyourpeas** [comment]
What is the use case? E12 team see a filtered view of patients by organisation or trust already. If they want to change trust, they do this on the previous page in organisation view? (see image)
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/1058647/232212758-e036ad8b-826f-4273-ba21-e3c5cc044682.png">
Otherwise, we can squeeze more dropdowns into the header of the patient table, possibly by reducing the space taken up by the National view button but it will likely look quite crowded, and may confuse the user if they are changing trusts in 2 different places in the workflow.
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/1058647/232213083-f7cddab7-221e-4eca-96e6-82b078ce832d.png">

**Comment by eatyourpeas** [comment]
closing this for the moment. If this feature is still needed in future we can revisit.
