### ISSUE TITLE
Tooltips for KPI table

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#375]
Here's the tooltips for the KPI table

KPI | Reference 
--- | ---
|1. Paediatrician   with expertise in epilepsies | Percentage of children with epilepsy, with   input by a 'consultant paediatrician with expertise in epilepsies' within two   weeks from first paediatric assessment
|2. Epilepsy Specialist Nurse | Percentage of children with epilepsy with input by an epilepsy specialist nurse by first year
|3a. Tertiary Input | Percentage of children meeting defined criteria for paediatric neurology   referral, with input of teriary care and/or CESS referral by first year
|3b. Epilepsy Surgery Referral | Percentage of ongoing children meeting defined Children's Epilepsy   Surgery Service (CESS) referral criteria with evidence of CESS referral
|4. ECG | Percentage of children with convulsive serizure and epilepsy, with an ECG   at first year
|5. MRI | Percentage of children with defined indications for an MRI, who had   timely MRI brain within 6 weeks of request
|6. Assessment of mental health issues | Percentage of children with epilepsy where there is documented evidence   that they have been asked about mental health either through clinical   screening, or a questionnaire/measure
|7. Mental health support | Percentage of children with epilepsy and a mental health problem who have   evidence of mental health support
|8. Sodium Valproate | Percentage of all females 12 years and over currently on valproate   treatment with an annual risk acknowledgement form completed
|9a. Care planning agreement | Percentage of children with epilepsy after 12 months where there is   evidence of items a, b and c.
|a. Patient-held individualised epilepsy document/copy of clinic letter that includes care planning information | Percentage of children with epilepsy with evidence that care planning   includes a patient held individualised epilepsy document or copy clinic   letter that includes care planning information.
|b. Patient/carer/parent agreement to care planning | Percentage of children with epilepsy with evidence of   patient/carer/parent agreement to the care planning.
|c. Care planning has been updated when necessary | Percentage of children with epilepsy with evidence that care planning has   been updated when necessary.
|9b. Care planning content | Percentage of children diagnosed with epilepsy with documented evidence of communication regarding core elements of care planning (items a - f)
|a. Parental prolonged seizures care plan | Percentage of children with epilepsy who have been prescribed rescue medication and have evidence of w written prolonged seizures plan
|b. Water safety | Percentage of children with epilepsy with evidence of discussion regarding water safety
|c. First aid | Percentage of children with epilepsy with evidence of discussion regarding first aid
|d. General participation and risk | Percentage of children with epilepsy with evidence of discussion regarding general participation and risk
|e. SUDEP | Percentage of children with epilepsy with evidence of discussion regarding SUDEP and evidence of a prolonged seizures care plan
|f. Service contact details | Percentage of children with epilepsy with evidence of being given service contact details
|10. School Individual Health Care Plan | Percentage of children with epilepsy aged 4 years and above with evidence of a school individual healthcare plan by 1 year after first paediatric assessment.

**Comment by pacharanero** [comment]
@AmaniKrayemRCPCH these have been reviewed and checked one by one in the UI. They are all now identical except for instances where the term "children and young people" has been substituted for just "children", and since I understood CYP to be the preferred term I have updated them all to use CYP, although I can change it back if needed. One or two minor typos or grammar errors were also fixed.

The canonical source of truth on these tooltips now is the content of the "reference" section of each of the field declarations in the kpi.py file
https://github.com/rcpch/rcpch-audit-engine/blob/live/epilepsy12/models_folder/kpi.py

The best way to propose future changes is to either open an issue on a specific line of code (which GitHub allows you to do) or to make changes in the GitHub UI and propose a Pull Request. In both cases the change will be reviewed by developer team before going into live so don't worry. (We can guide you through the process of doing these operations in GitHub).
