### ISSUE TITLE
Update bar chart labels

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#407]
- [ ] Can we change the legend key from 'Number achieving this measure' to 'Number of Health Boards/Trusts achieving this measure'
- [ ] apostrophe encoding issue - see y axis labels in below image

![Image](https://user-images.githubusercontent.com/126471383/232497314-760ff294-f6cf-4d52-aa52-b358d37a0e8f.PNG)

**Comment by eatyourpeas** [comment]
I have made this change but am slightly worried it is not quite true? It would be truer to say what is there already - since it is counting the number achieved or failed measures at a given level of abstraction.  The lowest level the young people are filtered at is the organisation. The organisations are then filtered based on which ICB, NHS region or whatever they fall in. But what is actually counted finally is the number of measures, not the number of trusts at a given level of abstraction achieving the measures.

**Comment by AmaniKrayemRCPCH** [comment]
Ah ok. I think the 'Number of Health Boards/Trusts achieving this measure' actually refers to organisational measures, which we aren't collecting on this platform yet (e.g. does your trust offer video telemetry?). That's my error. 


Perhaps a better label would be "Percentage/Number of children achieving this measure". I think in the past we've used the average **percentage** of patients meeting the measure, as each OPEN UK region will have a different number of patients and trusts.  Would it be possible to calculate percentage? E.g. 


![Image](https://user-images.githubusercontent.com/126471383/232720000-78111c97-0b23-43ce-a8f8-b11e78c25f4e.PNG)
