### ISSUE TITLE
All permissions views need testing

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#435]
Relates testing issue #350 

The views visible for VIEW_ONLY_PERMISSIONS  user type appear un-predictable:

- trying to add a child, when logged in, takes to log in page, even though already signed in
- can see national view - potentially related to #434 
- also NATIONAL_VIEW permissions are allowed to change their own role

Likely requires testing of each groups permissions

**Comment by eatyourpeas** [comment]
Some of this is now fixed, but the central issue of including tests remains open. To define this issue a little more clearly:

- [x] add testing framework: currently pytest, but this needs replacing with django specific testing framework
- [x] implement tests to ensure that view only users cannot edit models
- [x] implement tests to ensure that any user where is_staff is False and is_rcpch_team_member is False and is_superuser is false can neither view nor edit patients outside their trust. Models to test against in particular are Case, Site, Registration, Epilepsy12User as a priority. Additionally the same tests against FirstPaediatricAssessment, EpilepsyContext, MultiaxialDiagnosis, Episode, Syndrome, Investigations, Management, AntepilepsyMedicine. Expected behaviour is to return a 403.

There will be more tests that are needed but these core 2 test types are the most important.

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH to provide list of people + permissions  pls

**Comment by AmaniKrayemRCPCH** [comment]
**Audit centre**
- Audit centre lead clinician - Can create, edit, view and delete users in their trust. Can create, edit, view and delete patients, and transfer patients in their trust. Can create, edit, view and delete patient records.
- Audit centre clinician - Can view all users in their organisation, but cannot create, edit or delete users. Can create, edit, view and delete patients. Can create, edit, view and delete patient records.
- Audit centre administrator - Can view users in their organisation, but cannot create, edit or delete users. Can create, edit and view patients (add a patient). Can only view patient records.
RCPCH

Only need these three, ie. don’t need manager 

**RCPCH**
- RCPCH Audit Lead - Can create, edit, view and delete users nationally. Can create, edit, view, delete and transfer patients nationally. Can create, edit, view and delete patient records nationally. 

Rename to ‘RCPCH Audit team’ 

Don’t need analyst or admin, all E12 project team members will need full access. 

@anchit-chandran  This is the final list

**Comment by anchit-chandran** [comment]
Thanks Amani, now implemented! Closing as complete
