### ISSUE TITLE
Documentation tab label

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#492]
During user testing, a user contacted me saying that she could not enter data. She said she took the following steps:

![Image](https://user-images.githubusercontent.com/126471383/239190436-cb866a3e-3660-4adf-bc67-a1151e7939e2.PNG)

The confusion appears to be around the word 'Documentation', which implies that it contains patient records. Do we think it's worth using a different name? 'About this Website'?

**Comment by eatyourpeas** [comment]
The documentation link is only viewable once you are logged in and takes you here:
<img width="1386" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/b351e8ce-79dd-4c9f-a54e-60dd53b8f69c">
There is no authentication here though so my guess is that her organisation has a firewall preventing her reading it because that content is piped in from GitHub pages.
The wording I would say is up to you @AmaniKrayemRCPCH . I am not sure that the word documentation implies patient records though. I got paperwork with my new boiler 2 weeks ago that was referred to as 'documentation'. We could use the word Guidance, if you prefer, or, as you say, 'About the Epilepsy12 Platform' or similar. Main thing is to keep it short so it does not crowd the nav bar. Let us know what phrasing you prefer and we can make the change.
Thanks for posting the feedback.

**Comment by AmaniKrayemRCPCH** [comment]
Hi Simon, 

Sorry about the confusion - she'd opened the documentation tab successfully but then clicked the repository link at the top right when she couldn't find the patient records. That's where she was met with the error. 

I would lean towards the term 'Guidance'.

**Comment by eatyourpeas** [comment]
fixed by #495
