### ISSUE TITLE
Database access for E12 staff

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#534]
Conversation for E12 independent access to the postgres database to run their own queries.
- [ ] @nikyraja to check with IG about this
- [ ] think about how this would work practically

**Comment by anchit-chandran** [comment]
Sprint call 2023-08-04:

Step 1:

- implement Fridah button with large .csv file download with all columns

Step 2:

- API, including endpoint which reflects the above behaviour, and additional endpoints for more granular data download options

**Comment by eatyourpeas** [comment]
just to update this issue - discussion covered 3 options:
1. E12 team to have access to a parallel synchronised instance of the postgres database and pull down what information they need as and when
2. use the fridah button to download individual tables
3. expand the endpoints in the API as above

We left it that we would go with option 1 for the moment but work towards option 3 as a new feature to implement depending on what common queries E12 team would need.

**Comment by pacharanero** [comment]
Decision at E12 Issue Prioritisation Meeting 31.08.23 not to allow direct access to the DB for E12 staff since DB access would be problematic due to:
* encryption at rest of the DB data
* security implications of having full DB access
* * Operational rsk due to being able potentially to damage the DB and break the E12 application.

Instead data will be accessed via **API** or **download button**. @eatyourpeas @pacharanero
