### ISSUE TITLE
Administrator user- can't add new patients

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#539]
Trying to add new patients logged into the administrator account (nnap@rcpch.ac.uk) and I keep being sent to the log-in page every time i click 'add a new child/young person'. 

I get sent to the log-in page, but it doesn't actually work. Then, when I eventually log in, i get an access denied error. 

https://user-images.githubusercontent.com/126471383/258150529-1576b114-c2f0-4576-8285-eb90737c95a6.mp4

**Comment by anchit-chandran** [comment]
This could be another older version problem. @eatyourpeas looking at the form on latest version, as an audit_centre_administrator, I also can't create a child on pressing submit. console says date of birth is required. Looking at the form (screenshot below)- that input (and NHS number) isn't rendering.



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/f34b994e-ed83-45a7-9fe5-3112ff1e15b4)


 In the code, looks like this is expected behaviour (conditionally render DoB/NHS num if they have the right perms group) - is this what we want? It prevents them from creating cases


![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/ef6fb183-c330-4f67-b123-dfef8fa10c22)

Administrators SHOULD be able to create cases:



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/2495fc1e-770e-47a8-b8fb-77ec38d22378)

**Comment by eatyourpeas** [comment]
this has been fixed
