### ISSUE TITLE
Testing emails

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#542]
Email sending needs testing in all areas. Pls E12 to confirm workflow

**Known issues**

- pt transfer emails get sent to everyone

Q's for E12:

1. If clinical lead doesn't exist, goes to inbox. E12 to provide text for email

**Comment by AmaniKrayemRCPCH** [comment]
Here's the email text

"Dear Epilepsy12 Team,

A patient has been transferred from (sending trust) to (receving trust) by (user).
You are receiving this email because (receiving trust) does not have a Clinical Lead user registered to the Epilespy12 platform. "

If we feel we shouldn't include user details in the email, then that part can be omitted.

**Comment by anchit-chandran** [comment]
Related to #538

**Comment by eatyourpeas** [comment]
the edit centre but not the transfer centre button has been removed in the latest update. The email text has been changed.
