### ISSUE TITLE
trust mergers

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#579]
Heya, 

I'm aware that theres been at least one Trust merger since I gave you the organisation list. E.g. Yeovil district hospital is now under Somerset NHS Foundation Trust. How will we be handling trust mergers?

One of our pilot teams is Yeovil hospital, so it would be good if they could be put under the new trust in time for the pilot.

**Comment by anchit-chandran** [comment]
Solution would depend on nature of mergers. Each Organisation essentially has a dropdown where you can assign the Trust (only in admin superuser panel).

Currently, all the Organisations are seeded from the list you provided, I've updated this now:



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/4f15b045-4c74-4893-8df4-47dd4c53b9ae)



After going live, if/when there are further mergers, this can already be updated in the admin panel (only accessible to superusers).

My queries would be:

1. **rough estimate on how often this will happen?** Infrequent = RCPCH developer / superuser can update. Frequent, we might have to think of a user interface solution where RCPCH staff could make the updates @eatyourpeas ? I'm hesitant to allow anyone else, as the Trust plays a key role in many parts of the app; an incorrect change by a random person could have a big impact.

2. **will it just be re-assigning an organisation's Trust to another existing Trust OR are new Trusts formed?** Same solution would apply either way but just good to know
3. **Anything else to be aware of?**

**Comment by AmaniKrayemRCPCH** [comment]
Thanks Anchit

i. We've kept a record of mergers that we are informed of. We've been informed of 16 mergers since 2017. There may have been more that we weren't told about. 

ii. Sometimes one trust absorbs another. Sometimes they form a new trust. Sometimes there's a new ODS code, and sometimes they retain one of the original trust's ODS codes. 
e.g. Somerset NHS Foundation Trust absorbed Yeovil District NHS Foundation Trust, and kept the Somerset NHS Foundation Trust ODS code of RH5. 

iii. Mergers are recorded by NHS digital here - https://digital.nhs.uk/services/organisation-data-service/news-and-alerts/mergers-and-acquisitions

**Comment by eatyourpeas** [comment]
So to my mind there are 2 ways to approach this.
If it is important that we report data accurate at that time that it is published (ie that the configuration of organisation and trust reflects the situation at the time), we need to version the organisation model, so that each time there is a merger, the table is updated to reflect the new relationship with the trust model and the old relationship is persisted with a timestamp.
This is doable and probably needs doing before go live though will need some time. We would hook into celery beat and use the ODS API periodically to pull down any changes.

The alternative is that we change the relationship with Trust for individual organisations as they change. This is easily done in the admin. That way though the organisation becomes affiliated with the new trust and all current and historical reports would be calculated using this arrangement, so the historical relationship would be lost. It is way easier to do though.

From: Amani Krayem ***@***.***>
Date: Friday, 22 September 2023 at 10:46
To: rcpch/rcpch-audit-engine ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rcpch/rcpch-audit-engine] trust mergers (Issue #579)

Heya,

I'm aware that theres been at least one Trust merger since I gave you the organisation list. E.g. Yeovil district hospital is now under Somerset NHS Foundation Trust. How will we be handling trust mergers?

One of our pilot teams is Yeovil hospital, so it would be good if they could be put under the new trust in time for the pilot.

**Comment by eatyourpeas** [comment]
Just as an update - mergers are actually quite common. See [here](https://digital.nhs.uk/services/organisation-data-service/news-and-alerts/mergers-and-acquisitions) for a summary in the last 2-3 years.

Currently we store one record for each trust and each organisation (as well their relationship). If we are to report historical names and relationships (ie reflect the state of play in our reports at the time the report was produced), we will need to add versioning to the trusts and organisations. Ideally we would do this now before it starts filling up with data. @AmaniKrayemRCPCH, how important is it that our reports reflect organisation names/trust relationships accurate at the time the report was produced?

**Comment by AmaniKrayemRCPCH** [comment]
@nikyraja what do you think?

**Comment by pacharanero** [comment]
Just a quick note to add that adding versioning of trusts could potentially massively increase the complexity of the software. If a Trust merges, splits, or changes in any other way during the E12 reporting year we will have headache of deciding how to represent this in the data, where some data will belong to one trust, and then later in the same year the data will switch to belonging to a different trust. I would suggest we think long and hard about the necessity for this additional complication, and whether it is simpler and more robust just to ignore historical names/trust relationships. The additional work is not small and the concern for me would be that it could introduce new coding errors quite close to go-live.

**Comment by nikyraja** [comment]
Thanks all for the extra info and discussion here. 

In short, lets not time stamp/version the Trusts.

So currently, we account for Trust mergers in whole cohorts so in the annual analysis, all data would be merged regardless of when the merger actually happened. So the issue Marcus raised hopefully won't apply. We also only take into account mergers that have been communicated to us, so there are definitely more on NHS digital that aren't reflected in our data. This is because we currently manually merge data and as this is very time consuming, we only do it for those we have been directly contacted by, We also only account for mergers communicated by the data download date, so if a trust merged on 15/01 for example, their data would only be merged in the next year. We don't need any time stamp, we will just continue keeping a log of all the mergers in our files.

Therefore, I'm happy to just update the Trust with the drop down option Anchit described when this occurs, and we can aim to have this done by the last working day in December etc ready for the January download. I am also happy for only the developers to be able to do this. If it is simple to update mergers this way, we could look into using the NHS digital information to keep our reporting more accurate!

As for longitudinal analyses, I don't see this being an issue either as we will retain the original downloads which will be at organisation level. With our merger log, we can easily track back and analyse/report data before mergers etc, and can include this caveat etc.

**Comment by eatyourpeas** [comment]
Thank you @nikyraja this is really helpful guidance.
I will close this issue now but for the future just so you all know I have:
1. updated all the geographical boundary files with a ```publication_date``` field, so that it should be possible in future to introduce a versioning system for these if they change in future
2. updated the Organisation and Trust models to have ```active``` and ```publication_date``` fields which might allow versioning in future
3. Included the ORD ODS API URL in the credentials - there is no authentication necessary. I have added functions in the ```general_functions``` folder which can poll the API for latest changes (in the last month) to organisations like name change or affiliation and filter our database for any changes. This latter bit is not implemented but the code runs and could be hooked up in time through celery as a scheduled monthly job.

The devil is in the detail here - once implemented, we would need to update all the  filter and aggregation queries to select the correct version of each trust or organisation before running the calculations. This would need thinking about and testing. And actually this is ripe for abstracting out into its own module/repository that the work could be developed and maintained separately.

Hopefully at least as it is in its current form it might be possible to implement versioning in future without breaking existing data.

**Comment by AmaniKrayemRCPCH** [comment]
Heya, 

Can I just check that the latest mergers from https://digital.nhs.uk/services/organisation-data-service/news-and-alerts/mergers-and-acquisitions have been applied? The ones needed soonest are the bottom two on the list.

What is the process for future mergers? Shall I just raise an issue?

**Comment by AmaniKrayemRCPCH** [comment]
^following up on the latest comment here @eatyourpeas
