### ISSUE TITLE
Data Dictionary for Epilepsy 12

### ISSUE THREAD

**Issue by hannahevansrcphacuk** [rcpch/rcpch-audit-engine#602]
Hi,

Amani has created a table that shows how questions asked on the platform correspond to the variables that are exported from the platform as output data. Please see attached below:
[Round 4 Clinical Audit Dataset_New Platform_v1.pdf](https://github.com/rcpch/rcpch-audit-engine/files/13113816/Round.4.Clinical.Audit.Dataset_New.Platform_v1.pdf)
I wondered if the same could be done for the categories too? For example 1="Yes", 0="No" in the answer options column.
Please get in touch if you have any questions. Thank you in advance.
Best wishes,
Hannah

**Comment by pacharanero** [comment]
Hi @hannahevansrcphacuk - I think the information you need should be in the `epilepsy12/constants/` folder within this repository.

For example, the Ethnicity data is encoded using the constant `ETHNICITIES` in this file
https://github.com/rcpch/rcpch-audit-engine/blob/development/epilepsy12/constants/ethnicities.py

https://github.com/rcpch/rcpch-audit-engine/blob/980688791cb593359ebb4bd141e609e64bc5e66a/epilepsy12/constants/ethnicities.py#L1-L19

If you explore that `constants/` folder I think you should hopefully find everything you need to populate the document. You can search the GitHub repository to find anything that it isn't immediately obvious where to find.

The computer code in the repository should be viewed as the 'canonical' version, or the 'source of truth', so I would try to refer back to the code rather than creating a duplicate in the document. You could link to each constant file from your document perhaps? That way if there are ever any changes to the encoding system we use, you will always be looking at the latest version.

@eatyourpeas @anchit-chandran anything to add to the above?

**Comment by eatyourpeas** [comment]
That is correct.
