### ISSUE TITLE
Docs site is broken if link directs to /docs (without trailing slash)

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#608]
Can anyone tell me why the exact same code running in two different places would behave this way?

On local development, with the same .env, we get the Guidance link in the top right pointing to `https://e12.localhost/docs` on hover.
On click, this somehow gets a trailing slash added and it works:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/bf36261a-d43a-4fc5-b6cb-bf329fa74a01)

On development VPS, the same Guidance link has the same `https://e12.localhost/docs` on hover.
But when clicked there is no trailing slash added, and it doesn't work:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/295cff2f-2dd6-4b6c-b540-f462226b25ec)

If you add the trailing slash manually:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/f1881a8a-6068-4d2a-b76a-91c822bde3cb)

Works fine.

So - yes - we can probably make the URL resolver in Django return the URL with a trailing slash. But it would be lovely to know why something is adding the trailing slash for us automagically in local dev but not in the exact same environment on a server.

**Comment by pacharanero** [comment]
For info this trailing slash mkdocs thing seems to be related to mkdocs itself and is mentioned in Material docs 
https://github.com/squidfunk/mkdocs-material/issues/2520

**Comment by pacharanero** [comment]
This is now fixed, possibly through a small tweak to the trailing slash in Caddyfile.

**Comment by tomekit** [comment]
We were experiencing exactly the same issue.

In our case when user was visting: https://docs.s3drive.app/setup/providers then left navigation was broken with e.g. link:
https://docs.s3drive.app/import/ instead of https://docs.s3drive.app/setup/import/. In other words directory path was lost.

This wasn't happening when served locally using: `mkdocs serve` or if you manually visited URL by force adding trailing slash: https://docs.s3drive.app/setup/providers/

In our case configuring hosting server to redirect to URLs always ending with trailing slash resolved the issue, but had no idea how to address it using just MkDocs alone.

**Comment by pacharanero** [comment]
I think in the end it was fixed because of having a reverse proxy server (Caddy) in front of the MkDocs instance
