### ISSUE TITLE
Issue opening e12.localhost in Safari

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#616]
On MacOS, following the documentation as per the development branch to open e12.localhost works perfectly fine in Chrome, but in Safari the server cannot be found.

This is likely due to a Caddy certificate error, if Safari is not properly using the certificate, which would be installed in the System at this point if the user has followed the docs correctly. The certificate may need to be manually installed into the Safari Browser, and updated accordingly in the documentation.

**Comment by pacharanero** [comment]
I wonder if the issue on Mac is due to this?

https://caddy.community/t/how-to-get-dockerised-caddy-to-use-self-signed-certs-for-local-dev-with-php-fpm-spa-vuejs/16802/2

Really not sure what the solution is here, there's not much else I can find
searching, and using a *.localhost local domain seems to be accepted for
Caddy generally. The domain is set in the .env so it could be changed to
something else like localhost on your machine to try to resolve?

**Comment by dc2007git** [comment]
Resolved in PR #630
