### ISSUE TITLE
Creating local docker compose file

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#619]
For the `django` container in `docker-compose.yml`, the final command for local development needs to be `python manage.py runserver 0.0.0.0:8000` instead of  `gunicorn --bind=0.0.0.0:8000 --timeout 600 rcpch-audit-engine.wsgi` for auto reload.

Currently, just commenting out one or the other can lead to human error of pushing the wrong command to the deployed VPS (already happened). Better to have a separate file to eliminate risk of this error

**Comment by pacharanero** [comment]
@anchit-chandran rather than creating a second `docker-compose.yml` file (which would have a knock-on effect on every single one of the `s/docker-*` scripts), I've implemented this a different way using a variable to control which command runs. This is probably better practice because it keeps EVERYTHING which is changing between deployment environments in that one `.env` file. One place for all of the configs and _only_ one place.

You can now configure in the `.env` what command you would like Django to run after the container has been started up.

The two main options are both in there, with one commented out. In prod use Gunicorn, in dev use the Django auto-reloading server.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/82170bde-bf6c-4f1e-a7cd-40dd5113c021)

There was a bit of a trick to getting these ENVs to evaluate correctly - they are being executed in the context of a shell command INSIDE the Django container, where the env vars are available.

It took us a while to work out the correct syntax (`$ENV_VAR` not `${ENV_VAR}`) and escaping (`$$ENV_VAR`) so that Docker Compose would not try to interpolate anything but would instead pass the command into Bash for the interpolation to happen there.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/947f226d-bfb0-4274-8b1a-afb5a6938b4a)
