### ISSUE TITLE
Appropriate user models for RCPCH team & Organisation Employer

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#657]
RCPCH staff shouldn't be listed as lead clinicians when they are members of the Audit Team.

If True for audit team member when creating the user, Organisation Employer should be listed as 'RCPCH', but at the moment has listed all of the audit team registered as King's College staff, even though we're RCPCH. Organisation Employer could also be blanked.

**Comment by eatyourpeas** [comment]
That is not how it works unless I have confused myself.
Some clinicians (eg @coldunk ) are both clinicians and epilepsy12 audit team members
Some RCPCH staff are not audit team members
That is why there are flags for each
The is_staff flag by contrast is django field and defines if the user has access to the admin

If a user is a clinician, they are associated with an organisation. If they are RCPCH staff, the organisation_employer will be left as None.

The difficulty (which is a small one) comes if we use the createsuperuser method which, if a user is a clinician as defined in the role, is allocated to King's since there is no way of choosing a trust in the createsuperuser inputs

It is possible there are edge cases here I have missed

**Comment by anchit-chandran** [comment]
Will close this issue as believe it just requires knowing the nuances of how we've set up the data model.

The superuser difficult I think is a non-issue as they are only a handful, and should be omitted from the data any way if considered for analysis.
