### ISSUE TITLE
Cohort dates card

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#684]
The current cohort should be the cohort with the soonest submission date, rather than the one that is recruiting, as that's where we want users to focus their data collection.

**Comment by eatyourpeas** [comment]
Thanks @AmaniKrayemRCPCH 
So a couple of things to clarify for the team.
The current cohort to Epilepsy12 colleagues represents the one where the submission date is most imminent, not the one actively recruiting.
In the card therefore there needs to be greater clarity around which cohort is represented in the tables below.
Suggestions welcome from @anchit-chandran and @dc2007git on the best way to illustrate this.
My tuppence: possibly in the card:
2 Rows, the first labelled as currently recruiting cohort number, start date/end date/submission date, the second row: cohort awaiting submission number, start date/end date/submission date + days remaining.
The in the case list, is there any need to colour the children differently based on cohort or is that overkill? It is possible already to filter by cohort.

**Comment by eatyourpeas** [comment]
Also, in the table, the header should show which cohort the data refers to. In time there will be a select to allow users to toggle between cohorts.

**Comment by eatyourpeas** [comment]
So this is a starter for 10 (please forgive the implementation is not beautiful - it is the concept I am after)
<img width="1338" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/c0043728-8a4e-4efd-8598-95e8d4d19f2d">
This renders both cohorts - the actively recruiting cohort (currently 7) and the cohort due next for data submission (currently 6)

And this is reflected in the table which defaults to the data submission cohort:
<img width="1350" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/2d5e3c32-b8cd-4649-9e52-d8ec2462dead">
Note here that the cohort referred to by the data is explicit now (and I have no cohort 6 data currently so that is showing as unavailable).

The code is so far in refactor-cohort-data

Problems with this approach are:
1. what to do with numbers of registrations in the 3rd tile - do we do this for both cohorts?
2. would need to add the same cohort to the individual kpi table also - if we add a toggle here between active and submission cohorts, it might be possible for the kpis table to show one cohort's data, while the individual measures table shows another, since the two partials are independent and make independent htmx-get requests. A way round this might be to subtly colour the two cohorts differently - say the active cohort is brighter than the submission cohort.
3. A good chunk of the year (eg after January and before December the active and submission cohorts would be the same. For example, in Feb 2024, cohort 6 would have submitted, cohort 7 would be actively recruiting and due to close 30th November. In this case, the UI would have to reflect this.
4. The IMD and ethnicity piecharts - do those aggregate just the cohort, or both cohorts and if both, do we allow the user to toggle between them.

So my worry is that introducing versioning of cohorts and the data that describes them has quite a lot of implications for the dashboard and what we want it to report and how we want it to look. A short term solution is that we constrain the tables to the submission cohort (cohort 6) until we are clearer what we want, but in so doing, the users will lose any dynamic reporting for the kids they enter in the active cohort (cohort 7).

Comments/observations gratefully received.

**Comment by pacharanero** [comment]
Great stuff @eatyourpeas and thanks for raising the issue @AmaniKrayemRCPCH.

I wonder if this is something we could actually bottom out in some kind of on-site collaboration, or at a push a remote pair programming/user feedback session, where we actually fiddle about with the UI with instant feedback from the E12 audit team?

Or (and possibly easier to arrange) - how about we create some Figma UI wireframes for this which would allow non-programmers to move the elements around (Figma's like Microsoft Paint, you can drag and drop elements) and give us a mockup of what the best looking UI would be like for them?

I have also seen people use Powerpoint's graphical tools (which many people are already familiar with) used in this way, to let non-programmer users mock up what they want to see. I'd be fine with any option, main thing is to get an informative, lean, and clear UI for our users.

**Comment by pacharanero** [comment]
We have updated `live` to display the following so that launch can proceed as planned today, however the Issue here can remain open as we do want to evolve the UI in this card.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/5f32d9cf-6e8a-4b16-8123-b7b46986d2f0)

### Still TODO
* [x] extract the Cohort Data Card out into its own Partial and `include` it 
* [ ] update the card to include data about the Currently Recruiting Cohort as well as the Currently Submitting Cohort. (possibly using wireframes as above to ensure the design is agreed.

**Comment by anchit-chandran** [comment]
@dc2007git are you fine to do this?

**Comment by dc2007git** [comment]
> We have updated `live` to display the following so that launch can proceed as planned today, however the Issue here can remain open as we do want to evolve the UI in this card.
> 
> ![image](https://private-user-images.githubusercontent.com/2348385/288047381-5f32d9cf-6e8a-4b16-8123-b7b46986d2f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjYxODEsIm5iZiI6MTcwNTMyNTg4MSwicGF0aCI6Ii8yMzQ4Mzg1LzI4ODA0NzM4MS01ZjMyZDljZi02ZThhLTRiMTYtODEyMy1iN2I0Njk4NmQyZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTMzODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA1ZDdmMDU5MzM0YTVkZThlOTlkM2M5MGFlOTA3ODVmMmQ3MTRiNTEwNDU1MmQ2ZWJjNWVkMGE4N2NiMTE3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PDkYEZTJ3fTf63OB8SFobdLXcSQ304pD05l4q5tO5F4)
> 
> ### Still TODO
> * [x]  extract the Cohort Data Card out into its own Partial and `include` it
> * [ ]  update the card to include data about the Currently Recruiting Cohort as well as the Currently Submitting Cohort. (possibly using wireframes as above to ensure the design is agreed.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/86f74599-5eaf-453e-9607-d08fab66ec2b)

@pacharanero @anchit-chandran @eatyourpeas I have thrown together a quick wireframe inspired by Simon's, but just horizontally displaying the data to keep the organisation summary cards roughly the same length.

Let me know if you're happy for me to code this up or if you have any other design suggestions!

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH are you happy with this?

**Comment by AmaniKrayemRCPCH** [comment]
Looks good! I'd suggest swapping them around so the submitting cohort is on the left.
