### ISSUE TITLE
Clarity around one-time login code

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#702]
**1. Enter code page**

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/a3c21507-00d7-4193-a6e8-3600c795d7a4)

Is it possible to change the text shown depending on the users authentication method. 
 "Enter the code sent to your email" or "Enter the code visible in the Microsoft Authenticator app" - can play around with the wording

**2. Consistent language** 

- the email calls it an OTP code and a one-time login code
- the platform calls it a token

I personally think we should use "one-time login code" throughout as it makes the most sense to people unfamiliar with the term.

**Comment by pacharanero** [comment]
Thanks @AmaniKrayemRCPCH and I agree we should be using consistent language which the general public would understand, since really our end-users such as local audit administrative assistants are not going to be technicaly adept.

I have seen the relevant areas of code fairly recently so I'm happy to look into this today.
