### ISSUE TITLE
Updates to organisations - Add 2, remove 1

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#729]
These are updates to the organisations under Sherwood Forest Hospitals NHS Foundation Trust, as requested by @coldunk 

Add the following:
```
    {
        "OrganisationID": "",
        "OrganisationCode": "RK5HP",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "NEWARK HOSPITAL",
        "Address1": "BOUNDARY ROAD",
        "Address2": "",
        "Address3": "",
        "City": "NEWARK",
        "County": "NOTTINGHAMSHIRE",
        "Postcode": "NG24 4DE",
        "Latitude": "53.06751",
        "Longitude": "-0.80616",
        "ParentODSCode": "RK5",
        "ParentName": "SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E10000024",
    },
    {
        "OrganisationID": "",
        "OrganisationCode": "RK5CP",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "KMH COMMUNITY PAEDIATRICIANS",
        "Address1": "KINGS MILL HOSPITAL",
        "Address2": "MANSFIELD ROAD",
        "Address3": "",
        "City": "SUTTON-IN-ASHFIELD",
        "County": "NOTTINGHAMSHIRE",
        "Postcode": "NG17 4JL",
        "Latitude": "53.13455582",
        "Longitude": "-1.233566165",
        "ParentODSCode": "RK5",
        "ParentName": "SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "sfh-tr.pet@nhs.net",
        "Website": "http://www.sfh-tr.nhs.uk",
        "Fax": "01623 621770",
        "LocalAuthority": "E07000170",
    },
```

Remove the following:
```
    {
        "OrganisationID": "",
        "OrganisationCode": "RK540",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "SHERWOOD COMMUNITY HEALTH CENTRE",
        "Address1": "ELMSWOOD GARDENS",
        "Address2": "",
        "Address3": "",
        "City": "NOTTINGHAM",
        "County": "NOTTINGHAMSHIRE",
        "Postcode": "NG5 4AD",
        "Latitude": "52.98385661535865",
        "Longitude": "-1.1409483690398214",
        "ParentODSCode": "RK5",
        "ParentName": "SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E06000018",
    },
```

**Comment by eatyourpeas** [comment]
Just to add that updating/creating and deleting organisations is a workflow that is ripe for automating and has some complexity.
Just updating the RCPCH_ORGANISATIONS constant will not in itself update the database, but is a necessary step in the process. The workflow needs to be:

## Deleting an organisation
1. check there are no children associated with this organisation. If there are, it must not be deleted
2. Delete the organisation in the admin. This will delete any relationships it also has with associated trusts/health boards etc as well KPIAggregation models

## Updating an organisation
1. This can be done reasonably straightforwardly in the admin. Note that the ODS Code is a unique identifier and if the update includes an update to this, you are in effect creating a new organisation, rather than editing an existing one. Better therefore to create a new organisation and delete the old. This becomes more complicated if there are children associated with this organisation.

## Adding a new organisation
1. This can be done in the admin. The ODS Code must be unique. The name and ODS code should ideally be mandatory fields but are not currently prescribed as such in the model. Note that you must also allocate the Trust/Health Board, ICB, NHS England Region, London Borough and Country.
2. Add the same details to the RCPCH_ORGANISATIONS constant. This is necessary later when seeding the KPI Aggregation models
3. in the shell:
```python
>>> from epilepsy12.common_view_functions import _seed_all_aggregation_models
>>> _seed_all_aggregation_models()
```

**Comment by pacharanero** [comment]
@eatyourpeas this is great stuff! Would it be possible to add this to the Admins section of the E12 documentation site? Looks like something that would be good to have there.

**Comment by AmaniKrayemRCPCH** [comment]
To clarify, when we add new organisations, I just need to add them in admin and then raise an issue for the organisation to be added to the constant?

There's a couple more to add soon, but they can wait.

**Comment by eatyourpeas** [comment]
@AmaniKrayemRCPCH for the moment best just ask me and I will add them, as there needs to be a command run in the console to add them to the aggregation models too. I will think of a good way to automate this.

These are now live so closing this issue now. I have added the above steps to the documentation.
