### ISSUE TITLE
Unclear on how to delete patients

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#769]
Just had a call from a user who kept being logged out when they tried to delete a patient. They said they would go to the patient's audit record, click 'delete' under secondary care centre, and then the platform would log them out. 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/6364c886-51ba-4d4b-8bca-0ce426f58b86)

This user was from one of the sites that had multiple patients w/o organisations. I think that's the cause of that issue. 

My suggestions:
Maybe we should get rid of the 'delete' button under the secondary care centre. Is there a scenario where we'd delete but not transfer?

Another thought, maybe it should be clearer that these are two separate buttons? Maybe a gap between the buttons? Based on my call this morning, it seemed like the user hadn't realised that the 'edit' button leads to a different page.

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/ef72f79a-1102-4da1-99fa-b7e8317f3179)

**Comment by dc2007git** [comment]
Hi @AmaniKrayemRCPCH, happy to look into this. Do you have any information regarding which type of user was experiencing this problem (ie lead clinician, clinician, admin)?

Looking at the edit/audit button, I agree I think they should be more separated! We can do that.

**Comment by AmaniKrayemRCPCH** [comment]
Heya. The user was a lead clinician

Apologies I forgot to note, they meant to delete the patient and not the patient's organisation. They hadn't realised that that the edit button leads to a different page and thought the only way to delete a patient was to remove their secondary care organisation. So yes a bug to fix but also a UI issue and probably why were getting patients disappearing from organisations. 

i think i replicated this with patient 'Marley Cobb' on the staging site.

**Comment by dc2007git** [comment]
This is the new version of the button - a little more descriptive. Are you happy with this @AmaniKrayemRCPCH. Also, just for reference, the reason why the User was getting logged out was because he doesn't have permission to delete_lead_site - only the Audit Team does. So hopefully these buttons signpost to the user where they should go when they need to delete a child.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/cee6f184-8c85-4d21-9125-5b51ac15ffa8)

![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/b23bebe5-3639-458a-b22e-41187623b670)

@eatyourpeas from Amani's issue above - do you think there is a situation in which the user would have to delete but not transfer patients from the secondary care field? As we could then conditionally render the button only for the Audit team members - as they are the only ones with permission to do so anyway

**Comment by AmaniKrayemRCPCH** [comment]
Happy with the design of the button! Thanks for this!

@nikyraja and I agree that we're happy that there should just be a transfer button, and not delete. Technically, children could be discharged but then they would be ineligible for the audit. 

Maybe we could add a tooltip saying that if the patient is not being followed up/discharged, they are ineligible for the audit.
