### ISSUE TITLE
Backfill missing imd fields

### ISSUE THREAD

**Issue by mbarton** [rcpch/rcpch-audit-engine#843]
The RCPCH API server had some availability issues yesterday (12/03/24, extending into 13/03/24).

We should consider backfilling the IMD fields, at least for cases created or updated during that time. Until we do so, reporting by deprivation will miss some data.

**Comment by eatyourpeas** [comment]
Just to say on brief investigation there are 60 kids who have postcodes with no IMD, of which 9 are scored as no fixed abode etc. Should be simple to update the remaining 51 once we have more clarity over where the postcode data is coming from.

**Comment by eatyourpeas** [comment]
A further issue in troubleshooting this. Of the 51, all pass the validation test, though most have a hyphen which presumably then fails the IMD call. We should as part of this therefore add a further postcode validation step to remove any hyphens.

**Comment by eatyourpeas** [comment]
The latest update to live updated the Case model to include longitude and latitude and therefore involved looping through all the cases and resaving them. The whole thing took about an hour. The save() method in this had been refactored to remove '-' and capitalize postcodes. At the end of the operation, 31 postcodes had no associated IMD quintile, of these 15 look like postcodes (with no spaces and hyphens all caps). During the operation, there were 15 failures to calculate a quintile so that must have been the same 15. My guess is that these 15 have postcodes that are not in our postcode lookup service. This is about the best we are going to get so I am closing this here.
