### ISSUE TITLE
Organisational Audit

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#876]
To add the organisational audit to the platform. 

This is a form completed once a year. Only needs to be completed once per Trust/Health Board, and may only be completed by Lead Clinicians. 

The form is typically open from 1 November to 31 January. 
Ideally, this would be ready by 1 November 2024, but we can use Netsolving for another year if needed. 

The dataset is here - https://www.rcpch.ac.uk/work-we-do/quality-improvement-patient-safety/epilepsy12-audit/methodology-data-submission#downloadBox 
It's a total of 39 questions, some of which are routed.

**Comment by mbarton** [comment]
Agreed with @nikyraja we will add this to the platform for November 24.

There'll be a new tab with the [questions](questions here: https://www.rcpch.ac.uk/sites/default/files/2023-12/epilepsy12_round_4_organisational_audit_dataset_v1_20231128.pdf). We will try to re-use the styling from the existing patient data input wherever possible.

Anyone who can view a given organisation can fill in the audit for them.

Answers will be pre-filled based on last years submission which the E12 team will provide as a CSV and we will import manually. This is important as without pre-filling we think we will get significantly less responses due to the time it would take to fill it in again.

**Comment by nikyraja** [comment]
Thanks Michael! Here is a template CSV of the data, I've also added the key here for ease. 
[E12 Organisational Audit download template.csv](https://github.com/user-attachments/files/16192311/E12.Organisational.Audit.download.template.csv)
 
To note, the uploads with be for a wider Trust/Health Board and not for individual organisations. Will it be possible to set up the forms to be at Trust/Health Board level, or will they need to be at organisation? Can think of work arounds if needed.

**Comment by mbarton** [comment]
> Will it be possible to set up the forms to be at Trust/Health Board level, or will they need to be at organisation? 

That should be fine

**Comment by nikyraja** [comment]
We may want to add a few extra questions to what is already on the dataset, so will document these here:

- Q1.5. How many job planned hours are there per week (ESN and/or paediatrician) specified for epilepsy leadership and/or QI activities?

**Comment by mbarton** [comment]
> Thanks Michael! Here is a template CSV of the data, I've also added the key here for ease. [E12 Organisational Audit download template.csv](https://github.com/user-attachments/files/16192311/E12.Organisational.Audit.download.template.csv)

@nikyraja do you want the exported responses to the audit to be in the same format as this example?

There's some simplifications we can make like have a single column for multiple choice questions rather than one per option but I'll only do that if it would be useful for you.

**Comment by nikyraja** [comment]
Happy for you to simplify and make slicker!

**Comment by mbarton** [comment]
Closing as this is now implemented and will be refined under other issues
