### ISSUE TITLE
Eligibility Criteria

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#89]
I am not sure where the eligibility criteria are best confirmed in the flow, i would have thought that they are asked in registration and then if confirmed the child can then proceed through the later steps?  I would have thought with the confirmation of a first paediatric assessment this is also the point to capture the date of that assessment.  I would have though each eligibility criteria is worth capturing separately.  This might need a conversation?

Eligibility criteria:

This child...

is an NHS patient
AND
had a first paediatric assessment for an episode or episodes
AND
An episode and/or ongoing episodes were considered to be epileptic seizures
AND
this led to a diagnosis of epilepsy at some point
AND
has not had previous diagnoses of epilepsy or paediatric assessments for previous episodes considered epileptic.  (for these children that historic assessment would represent their first paediatric assessment and therefore would be likely outside the inclusion dates for ongoing cohorts)

(They may or may not have had an EEG)
(They may or may not have had regular epilepsy treatment)
(The term epilepsy may have not been actually been used but they have been treated as such in terms of a description of ongoing epileptic seizures or commenced on regular epilepsy treatment because of the risk of future seizures)

**Comment by eatyourpeas** [comment]
Hi,
 
I’ve pulled out the patient inclusion criteria we use in the audit for the API front end; updated because we’re moving away from including children with only non-epilepsy seizures. Colin, does this look ok to you too?
 
 
The child or young person:
is a patient in the NHS (of either an NHS Trust in England or an NHS Health Board in Wales)
has had two or more seizure episodes at least 24 hours apart, OR has been diagnosed with epilepsy for another reason
has been referred to a paediatric service* for a first assessment
has been referred for an initial EEG**, OR  a first EEG was indicated although the child was not actually referred
 
 
The child or young person has NOT:
requested to opt out
previously been diagnosed with epilepsy,
previously had a paediatric first assessment or EEG for earlier seizure episodes
previously been registered in the Epilepsy12 audit.
 
 
 
*= paediatric service, or a dedicated paediatric team based in A&E. They should not have been referred or assessed by an adult service/team.
 
** EEG for paroxysmal episodes considered as first EEG.  If previous EEG was for other reasons e.g. HIE, encephalitis then this EEG would not count as first EEG
 
Best wishes
 
Helen

I think criteria 4 About the EEG is redundant now as we used this really as a handle/proxy by which to identify the children fulfilling 1-3
The rest applies
 
As per discussion above: Item 4 left in currently but can remove in future in final proofs etc.

closed [48158c5](https://github.com/rcpch/rcpch-audit-engine/commit/48158c5c784e22db412be0afdb8979f0558669b6)

**Comment by coldunk** [comment]
i have reread these through and checked against our methodology.  I would suggest the following wording that is agreed on mass for each individual patient

**Inclusion**
The following criteria must ALL be fulfilled to verify registration for Epilepsy12

Is a patient within NHS England or Wales
AND
Has had a first paediatric assessment* for an episode(s) that was ultimately deemed to be epileptic
AND
Has had two or more epileptic seizure episodes at least 24 hours apart OR diagnosed with epilepsy for any other reason

**Exclusion**
The child or young person has had ONE OR MORE of the following exclusion criteria:

- requested to opt out of Epilepsy12
- previously been diagnosed with epilepsy before the first paediatric assessment
- previously had a paediatric assessment (definition below) for earlier seizure episodes considered to be epileptic
- previously been registered in the Epilepsy12 audit
- has gone on to have ongoing care within the first year of care for their epilepsy provided by adult or non-NHS services

by an inpatient our outpatient, hospital or community paediatric service, or a dedicated paediatric team based in ED.

**Comment by eatyourpeas** [comment]
fixed by [09eeaa9](https://github.com/rcpch/rcpch-audit-engine/commit/09eeaa9eb859ed4ebf920b4a39abdf78b00a1f0a)

**Comment by coldunk** [comment]
this text 

"** EEG for paroxysmal episodes considered as first EEG. If previous EEG was for other reasons e.g. HIE, encephalitis then this EEG would not count as first EEG"

is redundant now and can be deleted
