### ISSUE TITLE
Viewing locked audit records

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#893]
If a user is accidentally assigned to cohort 5, I can't easily go in and edit that
Similarly, I can't view 'submitted' records without unsubmitting them. 

Is it possible to do the following:
* for records where the deadline has passed, allow users to open and read these. Allow RCPCH staff to edit these
* for submitted records, allow all users to open and read these. These still need to be 'unsubmitted' for anyone to make edits.

Let me know if there's a better solution.

**Comment by eatyourpeas** [comment]
This might be hard to implement @AmaniKrayemRCPCH because by re-enabling the row, the users existing permissions would apply: it is of course possible to give them editing permission for one cohort, and view only permission for another, but will take a bit of time. I could potentially give just RCPCH access to o those disabled rows - that would be the quickest fix to this. This way, all cohorts would be viewable and editable to RCPCH only - could that work?

**Comment by AmaniKrayemRCPCH** [comment]
agreed that it would be easier to give RCPCH staff edit access - as long as we're able to change the FPA date of a patient in cohort 5, or to delete them.

**Comment by eatyourpeas** [comment]
Just to add, this vulnerability should be historical. As per this code snippet below - the first paediatric assessment date minimum value now is set at the currently submitting cohort (currently 6), but earlier (date of birth) for RCPCH audit team
```python
if request.user.is_superuser or request.user.is_rcpch_audit_team_member:
        earliest_allowable_date = case.date_of_birth
    else:
        # registering a new child in the audit by a clinical team
        # sets the minimum allowable date to the currently submitting cohort start date
        earliest_allowable_date = cohorts_and_dates(
            first_paediatric_assessment_date=date.today()
        )["submitting_cohort_start_date"]
```
