### ISSUE TITLE
User Feedback on 'set' button for dates

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#968]
A few users have reported challenges where they have selected the date for input/investigation etc, but have not pressed the set button and the date therefore disappears. eg. 
![image](https://github.com/rcpch/rcpch-audit-engine/assets/115647429/f719184e-3b82-4a3b-8d20-a7d816d24d36)

Is there a way to make this easier for users? Could we remove the set buttons, and just have the dates save on their own? I can't recall the rationale for having the 'set' button?

If not, we could add "once the date have been entered, please press 'set' to save the entry" to the help note of each date question.

**Comment by eatyourpeas** [comment]
The dates used to save on their own on keyup or change of the value in the field, and worked well that way, but that relied on the fact that people used the date picker. When it was discovered that some were typing the dates then we discovered that we could not use that method, because the field would update as soon as the user had typed only a character or two, and this would trigger a rerender of that element. The only other way to allow it was to introduce a longer time delay but that was really clunky for those using the date picker. So we introduced the Set button, so that users could trigger the update when they were ready. There is no easy way round this unfortunately, since we cannot coerce them into using the date picker. 

In your example, there is already a pink tick, meaning that that date must be being edited, so the user here already knows to press the set button. If the field is unscored, the blue target icon will show until the date has been validated and stored. I am not sure I see a way out of this one, except for users to learn to press the set button. Paging @mbarton for suggestions.

**Comment by nikyraja** [comment]
Thanks Simon - the screenshot was just from me playing around and not actually from users. 

That's helpful information though, its not the end of the world, as you said users will just get used to the functionality. The tooltips may help with this.

**Comment by dc2007git** [comment]
Closing this unless @mbarton has suggestions
