### ISSUE TITLE
'See all children of' & 'See all users of' buttons being filled in with trust instead of organisation

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#981]
This bug seems to occur in development, not live. Where a user should see 'See all children of <insert organisation name here>', they instead see 'See all children of <insert Trust name here>', like below. This is also replicated for the 'See all users of' button:

<img width="891" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/65614251/55e7741e-2f2e-4912-905a-4ba05b479c30">

**Comment by eatyourpeas** [comment]
Sorry - this was a request from @AmaniKrayemRCPCH and @nikyraja - although this is an organisation view, users were not aware that they could view other organisations in their trust. If logged in as a clinician now it is possible for users to select between other same trust member organisations direct from the organisation landing page. If it is not working like that, please post here, otherwise feel free to close.

**Comment by dc2007git** [comment]
Okay perfect thanks for the reply @eatyourpeas !
