### ISSUE TITLE
Repeatedly asked to reset password

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#988]
This popped up today, so I reset my password:

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/9a9ba27c-6841-403c-b67a-7521225f5290)

However, I've logged in twice since and each time it asks me to reset my password. I can bypass it by clicking 'Home' in the top right.

**Comment by eatyourpeas** [comment]
I have tried this in staging, live and development and am finding the expected behaviour so I am not sure I can explain it. I have found a vulnerability though that once the password has expired on redirecting to the password reset page the user was not logged out, so it would be possible to click on the home link and stay logged in. I have fixed this in the next update but it does not solve your problem. Perhaps if you could try logging in, be redirected to the password reset page, enter your email and at that point logout. Then click on the link in the email and use this to reset the password. Then try logging in and report back here?

**Comment by mbarton** [comment]
Sorry for going on a tangent a bit but given we have two factor authentication I'm not sure expiring passwords buys us much additional security.

Disallowing passwords from known breaches (eg using the [haveibeenpwned](https://haveibeenpwned.com/API/v3#PwnedPasswords) database) would probably be a stronger defense.

**Comment by eatyourpeas** [comment]
I am happy with this - we only included it because it was specifically listed as a vulnerability in the PenTest report under amber. I think passwords are 10 characters for users, and 16 for superusers, with a 90 day password lifespan and a 30 minute lockout for more than 5 consecutive failed attempts.

**Comment by AmaniKrayemRCPCH** [comment]
It worked! I logged out before using the password reset link, and it hasn't asked again.

**Comment by eatyourpeas** [comment]
great thank you.
The next merge from staging into live should fix this then as it automatically logs people out when password has expired. This is currently not happening and I think leads to this error.
Once @nikyraja is happy I will merge staging into live and this will hopefully fix this issue.

**Comment by nikyraja** [comment]
thanks all! happy for this to be made live.

**Comment by eatyourpeas** [comment]
this is now merged. Please reopen if ongoing issues regarding password reset.
